huggingface:
  apitoken: "your_api_token"
  local_dir: "/tmp/cache/huggingface/local_repo"
  cache_dir: "/tmp/cache/huggingface"

mlflow:
  endpoint: "http://localhost:5001"
  experiment: "flan-t5-finetune-ita"